language: cpp
compiler:
  - gcc
before_install:
  - git submodule update --init --recursive
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install -qq p7zip-full qtdeclarative5-dev
script:
  - qmake -v
  - qmake
  - make
after_success:
  - cd ..; wget http://quazaa.ce3c.be/secret; wget http://quazaa.ce3c.be/id_dsa_sf.enc
  - secret=`openssl rsautl -decrypt -inkey ~/.ssh/id_rsa -in secret`
  - openssl aes-256-cbc -k "$secret" -in id_dsa_sf.enc -d -a -out id_dsa_sf
  - tarfile=Quazaa-TravisBuild-$(git rev-parse --short HEAD)-$(date +'%Y%m%d').tar
  - tar -cf $tarfile bin
  - gzip $tarfile
  - scp -oStrictHostKeyChecking=no $tarfile.gz ce3c@frs.sourceforge.net:/home/frs/project/quazaa/TravisBuilds/
notifications:
  email: false
  irc:
    channels:
      - "irc.paradoxirc.net#quazaa-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} - %{build_url}"
    use_notice: true
    skip_join: true


